kind: pipeline
type: docker
name: publish

trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  - name: docker
    image: plugins/docker
    settings:
      registry: r.s8k.top
      username: docker
      password:
        from_secret: DOCKER_REGISTRY_PASSWD
      repo: r.s8k.top/memo
  - name: deploy
    image: plugins/webhook
    settings:
      method: POST
      urls: https://deploy.s8k.top/api/services/memo/deploy
      headers:
        from_secret: COMPOSE_DEPLOYER_SECRET_HEADER
    depends_on:
      - docker
